/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Ohlc {
  open: number
  high: number
  low: number
  close: number
}
export function sma(series: Array<number>, period: number): Array<number>
export function ema(series: Array<number>, period: number): Array<number>
export interface Macd {
  line: number
  signal: number
  histogram: number
}
export function macd(series: Array<number>, fastPeriod: number, slowPeriod: number, smoothing: number): Array<Macd>
export function sd(series: Array<number>, period: number, std: number, mode: number): Array<number>
export interface BollingerBands {
  upper: number
  middle: number
  lower: number
  std: number
}
export function bollingerBands(series: Array<number>, period: number, std: number, stdMode: number): Array<BollingerBands>
export interface Kdj {
  k: number
  d: number
  j: number
}
export function kdj(series: Array<Ohlc>, period: number, kSignal: number, dSignal: number): Array<Kdj>
export function tr(lows: Array<number>, highs: Array<number>, closes: Array<number>): Array<number>
export function atr(lows: Array<number>, highs: Array<number>, closes: Array<number>, period: number): Array<number>
export interface Kc {
  upper: number
  middle: number
  lower: number
}
export function kc(lows: Array<number>, highs: Array<number>, closes: Array<number>, period: number): Array<Kc>
export function donchianMidline(lows: Array<number>, highs: Array<number>, period: number): Array<number>
export function highest(series: Array<number>, period: number): Array<number>
export function lowest(series: Array<number>, period: number): Array<number>
export function linearRegression(series: Array<number>, period: number): Array<number>
export function mean(lows: Array<number>, highs: Array<number>, closes: Array<number>, period: number): Array<number>
export interface Ttm {
  histogram: number
  squeezeOn: boolean
}
export function ttmSqueeze(lows: Array<number>, highs: Array<number>, closes: Array<number>, period: number): Array<Ttm>
export function testRun(series: Array<Ohlc>, w: number): void
